version: '3'

services:
  frontend:
    build: .
    container_name: base-next-app-router
    restart: always
    ports:
      - 8888:3000

  gitlab-runner:
    image: 'gitlab/gitlab-runner:latest'
    container_name: base-next-app-router-runner
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./gilab-runner-config:/etc/gitlab-runner
    restart: unless-stopped
