version: "3"

services:
  frontend:
    build: .
    container_name: react-base
    restart: always
    ports:
      - 3002:5005

  gitlab-runner:
    image: "gitlab/gitlab-runner:latest"
    container_name: react-base-runner
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./gilab-runner-config:/etc/gitlab-runner
    restart: unless-stopped
